[theme]
name = "github"

[theme.light]
fg_primary = "#1f2328"
fg_muted = "#59636e"
fg_accent = "#0969da"
bg_primary = "#ffffff"
bg_muted = "#f6f8fa"
bg_neutral_muted = "#818b981f"
bg_attention_muted = "#fff8c5"
bg_secondary = "#f6f8fa"
border_primary = "#d1d9e0"
border_muted = "#d1d9e0b3"
fg_sheen = "#1f2328"
bg_sheen = "#ffffff"
border_sheen = "#d1d9e0"
alert_note = "#0969da"
alert_tip = "#1a7f37"
alert_important = "#8250df"
alert_warning = "#9a6700"
alert_caution = "#cf222e"

[theme.dark]
fg_primary = "#f0f6fc"
fg_muted = "#9198a1"
fg_accent = "#4493f8"
bg_primary = "#0d1117"
bg_muted = "#151b23"
bg_neutral_muted = "#656c7633"
bg_attention_muted = "#bb800926"
bg_secondary = "#161b22"
border_primary = "#3d444d"
border_muted = "#3d444db3"
fg_sheen = "#e6edf3"
bg_sheen = "#0d1117"
border_sheen = "#30363d"
alert_note = "#58a6ff"
alert_tip = "#3fb950"
alert_important = "#d2a8ff"
alert_warning = "#d29922"
alert_caution = "#f85149"
